/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cloud/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeGoogleIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshCloudSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutCloudSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path?: never;
            cookie?: never;
        };
        get: operations["listHostedProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getHostedProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path?: never;
            cookie?: never;
        };
        get: operations["listHostedSessions"];
        put?: never;
        post: operations["spawnHostedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getHostedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/send": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendHostedSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/pr": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listHostedSessionPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/reviews": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listHostedSessionReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/workspace/files": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listHostedWorkspaceFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/workspace/file": {
        parameters: {
            query: {
                path: string;
            };
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["readHostedWorkspaceFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/terminal-ticket": {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically issues one connection ticket for the session sandbox mux.
         *     Replaying a consumed ticket fails; terminal bytes never traverse a
         *     control-plane terminal endpoint.
         *      */
        post: operations["createSandboxTerminalConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accepts the asynchronous project-placement saga. A successful response
         *     is not a project. Poll the returned operation until ready, then discover
         *     the canonical project through GET /api/v1/projects.
         *      */
        post: operations["createWorkspacePlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/workspaces/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                operationId: components["parameters"]["OperationId"];
            };
            cookie?: never;
        };
        get: operations["getWorkspacePlacement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listGitHubInstallations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startGitHubInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["disconnectGitHubInstallation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get: operations["listGitHubInstallationRepositories"];
        put: operations["setGitHubRepositoryAllowlist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncGitHubInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/github/installations/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeGitHubInstallation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/github/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically consumes one scoped bootstrap delivery. The bearer used for
         *     this request was delivered out of band in /run/ao/capability and is not
         *     repeated in either request or response.
         *      */
        post: operations["acknowledgeWorkerBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeatWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendWorkerSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkerSessionPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkerSessionReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/checkout-grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requests one scoped checkout delivery. The control plane returns only
         *     delivery state; repository credentials are installed by the sandbox
         *     delivery mechanism and never appear in JSON, argv, environment, or git
         *     configuration.
         *      */
        post: operations["requestWorkerCheckoutGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            code: string;
            details?: {
                [key: string]: unknown;
            };
            error: string;
            message: string;
            requestId?: string;
        };
        ListProjectsResponse: {
            projects: components["schemas"]["ProjectSummary"][];
        };
        ProjectGetResponse: {
            project: components["schemas"]["ProjectOrDegraded"];
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        ProjectSummary: {
            id: string;
            /** @enum {string} */
            kind: "single_repo" | "workspace" | "scratch";
            name: string;
            orchestratorAgent?: string;
            path: string;
            resolveError?: string;
            sessionPrefix: string;
        };
        ListSessionsResponse: {
            sessions: components["schemas"]["ControllersSessionView"][];
        };
        SessionResponse: {
            session: components["schemas"]["ControllersSessionView"];
        };
        ControllersSessionView: {
            activeAgentSwitch?: components["schemas"]["AgentSwitch"];
            activity: components["schemas"]["DomainActivity"];
            autoInjectCI: boolean;
            autoInjectReview: boolean;
            autoReviewEnabled: boolean;
            branch?: string;
            /** Format: date-time */
            createdAt: string;
            displayName?: string;
            harness?: string;
            id: string;
            isPinned: boolean;
            isTerminated: boolean;
            issueId?: string;
            kind: string;
            /** @enum {string} */
            mode: "chat" | "tui";
            model?: string;
            /** Format: date-time */
            pinnedAt?: null | string;
            /** Format: int64 */
            previewRevision?: number;
            previewUrl?: string;
            projectId: string;
            prs: components["schemas"]["SessionPRFacts"][];
            /** @enum {string} */
            reviewerHarness?: "claude-code" | "codex" | "copilot" | "cursor" | "kilocode" | "opencode" | "kiro" | "pi" | "qwen" | "agy" | "continue" | "goose" | "vibe" | "devin" | "droid" | "kimi" | "kimchi" | "muse" | "amp" | "aider" | "grok" | "crush" | "auggie" | "cline" | "autohand";
            /** @enum {string} */
            scmStatus?: "pr_open" | "draft" | "ci_failed" | "review_pending" | "changes_requested" | "approved" | "mergeable" | "merged";
            /** @enum {string} */
            status: "working" | "pr_open" | "draft" | "ci_failed" | "review_pending" | "changes_requested" | "approved" | "mergeable" | "merged" | "needs_input" | "exited" | "idle" | "terminated" | "no_signal";
            terminalHandleId?: string;
            terminateOnPrMerge: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        SpawnSessionRequest: {
            attachments?: components["schemas"]["AttachmentInput"][];
            branch?: string;
            displayName?: string;
            /** @enum {string} */
            harness?: "claude-code" | "codex" | "aider" | "opencode" | "grok" | "droid" | "amp" | "agy" | "crush" | "cursor" | "qwen" | "copilot" | "goose" | "auggie" | "continue" | "devin" | "cline" | "kimi" | "muse" | "kiro" | "kilocode" | "vibe" | "pi" | "kimchi" | "prime-agent" | "autohand";
            issueId?: string;
            /** @enum {string} */
            kind?: "worker" | "orchestrator";
            /** @enum {string} */
            mode?: "chat" | "tui";
            model?: string;
            projectId: string;
            prompt?: string;
            /** @enum {string} */
            trackerProvider?: "github" | "gitlab";
        };
        SpawnSessionResponse: {
            promptBytes: number;
            session: components["schemas"]["ControllersSessionView"];
            systemPromptBytes: number;
        };
        SendSessionMessageRequest: {
            attachment?: components["schemas"]["AttachmentInput"];
            message: string;
        };
        SendSessionMessageResponse: {
            message: string;
            ok: boolean;
            sessionId: string;
        };
        ListSessionPRsResponse: {
            prs: components["schemas"]["SessionPRSummary"][];
            sessionId: string;
        };
        ListReviewsResponse: {
            reviewerHandleId: string;
            reviewerHarness?: string;
            reviews: components["schemas"]["PRReviewState"][];
            runs: components["schemas"]["ReviewRun"][];
        };
        ListWorkspaceFilesResponse: {
            compareBaseRef?: string;
            compareBaseSha?: string;
            /** @enum {string} */
            compareMode?: "base" | "head_fallback";
            files: components["schemas"]["WorkspaceFileSummary"][];
            sessionId: string;
            truncated: boolean;
        };
        WorkspaceFileResponse: {
            additions: number;
            binary: boolean;
            compareBaseRef?: string;
            compareBaseSha?: string;
            /** @enum {string} */
            compareMode?: "base" | "head_fallback";
            content: string;
            contentTruncated: boolean;
            deleted: boolean;
            deletions: number;
            diff: string;
            diffTruncated: boolean;
            imageMediaType?: string;
            path: string;
            previousPath?: string;
            sessionId: string;
            /** Format: int64 */
            size: number;
            /** @enum {string} */
            status: "unmodified" | "modified" | "added" | "deleted" | "renamed";
        };
        ErrorEnvelope: {
            error: string;
            code: string;
            message: string;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        GoogleIdentityExchange: {
            idToken: string;
        };
        RefreshTokenInput: {
            refreshToken: string;
        };
        AOSession: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        OrganizationMembership: {
            /** Format: uuid */
            orgId: string;
            orgSlug: string;
            displayName: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        CurrentAccount: {
            user: components["schemas"]["CurrentUser"];
            organizations: components["schemas"]["OrganizationMembership"][];
        };
        CreateWorkspacePlacementInput: {
            displayName: string;
            /** Format: uri */
            repositoryUrl: string;
            /** @description Authoritative branch passed through the placement saga. */
            defaultBranch: string;
            config?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        WorkspacePlacementState: "pending" | "failed" | "ready";
        WorkspacePlacementOperation: {
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            orgId: string;
            state: components["schemas"]["WorkspacePlacementState"];
            defaultBranch: string;
            /** @description Present only when state is ready; discover its DTO through /api/v1/projects. */
            projectId?: string;
            failure?: components["schemas"]["PlacementFailure"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PlacementFailure: {
            code: string;
            message: string;
        };
        GitHubInstallation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orgId: string;
            /** @constant */
            provider: "github";
            accountLogin: string;
            accountType: string;
            appSlug: string;
            repositorySelection: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GitHubInstallationList: {
            installations: components["schemas"]["GitHubInstallation"][];
        };
        GitHubInstallationStart: {
            /** Format: uri */
            installUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        GitHubRepository: {
            id: string;
            fullName: string;
            private: boolean;
            allowed: boolean;
        };
        GitHubRepositoryList: {
            repositories: components["schemas"]["GitHubRepository"][];
        };
        GitHubRepositoryAllowlistInput: {
            repositories: string[];
        };
        GitHubWebhookAcceptance: {
            /** @enum {string} */
            status: "accepted" | "duplicate";
        };
        TerminalConnectionRequest: {
            /** @enum {string} */
            kind: "agent" | "workspace";
            /** Format: int64 */
            after?: number;
        };
        TerminalConnection: {
            /**
             * Format: uri
             * @description Authenticated sandbox mux WebSocket URL, never a control-plane relay URL.
             */
            connectionUrl: string;
            /** @description Single-use ticket consumed atomically by the sandbox mux. */
            ticket: string;
            /** Format: date-time */
            expiresAt: string;
            /** @constant */
            protocol: "ao.mux.v1";
        };
        WorkerBootstrapInput: {
            /** Format: uuid */
            deliveryId: string;
            version: string;
            capabilities: string[];
        };
        WorkerBootstrapGrant: {
            /** Format: uuid */
            deliveryId: string;
            /** @enum {string} */
            state: "consumed";
            scope: components["schemas"]["WorkerScope"];
            /** Format: date-time */
            consumedAt: string;
        };
        WorkerScope: {
            /** Format: uuid */
            orgId: string;
            /** Format: uuid */
            workspaceId: string;
            sessionId: string;
            /** @enum {string} */
            role: "coordinator" | "worker";
        };
        WorkerHeartbeatInput: {
            version: string;
            capabilities: string[];
        };
        WorkerStatus: {
            scope: components["schemas"]["WorkerScope"];
            /** @enum {string} */
            placementState: "pending" | "running" | "stopping" | "stopped" | "failed";
            /** Format: date-time */
            observedAt: string;
        };
        WorkerCheckoutGrantInput: {
            /** Format: uuid */
            deliveryId: string;
            repositoryId: string;
            /** @enum {string} */
            operation: "clone" | "fetch";
        };
        WorkerCheckoutGrant: {
            /** Format: uuid */
            deliveryId: string;
            repositoryId: string;
            /** @enum {string} */
            operation: "clone" | "fetch";
            /** @enum {string} */
            state: "pending" | "delivered" | "failed" | "expired";
            /** Format: date-time */
            expiresAt: string;
            failure?: components["schemas"]["PlacementFailure"];
        };
        AgentConfig: {
            mode?: string;
            model?: string;
            permissions?: string;
        };
        ContainerReapConfig: {
            disabled?: boolean;
        };
        RoleOverride: {
            agent?: string;
            agentConfig?: components["schemas"]["AgentConfig"];
        };
        DomainReviewerConfig: {
            harness: string;
        };
        TrackerIntakeConfig: {
            assignee?: string;
            enabled?: boolean;
            /** @enum {string} */
            provider?: "github" | "gitlab";
            repo?: string;
        };
        ProjectConfig: {
            agentConfig?: components["schemas"]["AgentConfig"];
            agentRules?: string;
            agentRulesFile?: string;
            autoReview?: boolean;
            containerReap?: components["schemas"]["ContainerReapConfig"];
            defaultBranch?: string;
            env?: {
                [key: string]: string;
            };
            orchestrator?: components["schemas"]["RoleOverride"];
            orchestratorRules?: string;
            postCreate?: string[];
            reviewers?: components["schemas"]["DomainReviewerConfig"][];
            sessionPrefix?: string;
            symlinks?: string[];
            trackerIntake?: components["schemas"]["TrackerIntakeConfig"];
            worker?: components["schemas"]["RoleOverride"];
        };
        WorkspaceRepo: {
            gitStatus?: string;
            name: string;
            relativePath: string;
            repo: string;
        };
        Project: {
            agent?: string;
            config?: components["schemas"]["ProjectConfig"];
            defaultBranch: string;
            id: string;
            /** @enum {string} */
            kind: "single_repo" | "workspace" | "scratch";
            name: string;
            path: string;
            repo: string;
            workspaceRepos?: components["schemas"]["WorkspaceRepo"][];
        };
        DegradedProject: {
            id: string;
            /** @enum {string} */
            kind: "single_repo" | "workspace" | "scratch";
            name: string;
            path: string;
            resolveError: string;
        };
        ProjectOrDegraded: components["schemas"]["Project"] | components["schemas"]["DegradedProject"];
        AgentSwitch: {
            /** @enum {string} */
            agentHandoffStatus: "not_attempted" | "requested" | "received" | "unavailable" | "timed_out" | "failed" | "rejected";
            /** @enum {string} */
            errorCode?: "daemon_restart_pre_stop" | "daemon_restart_post_stop" | "daemon_restart_unrecoverable_target" | "daemon_restart_before_delivery" | "delivery_unconfirmed" | "source_session_terminated" | "source_stop_unconfirmed" | "target_binary_missing" | "target_agent_unauthorized" | "target_start_unconfirmed" | "source_restore_unconfirmed" | "request_cancelled" | "source_blocked" | "failed_pre_stop" | "failed_post_stop" | "target_ready_failed" | "delivery_failed" | "switch_failed";
            fromHarness: string;
            id: string;
            /** Format: date-time */
            requestedAt: string;
            semanticHandoffIncluded: boolean;
            sessionId: string;
            /** @enum {string} */
            sourceTranscriptStatus?: "not_attempted" | "available" | "unavailable";
            /** @enum {string} */
            state: "preparing_handoff" | "stopping_source" | "source_stopped" | "starting_target" | "target_ready" | "delivering_context" | "completed" | "failed";
            targetHarness: string;
            /** @enum {string} */
            targetStartMode?: "fresh" | "resumed";
            /** Format: date-time */
            updatedAt: string;
        };
        DomainActivity: {
            /** Format: date-time */
            lastActivityAt: string;
            state: string;
        };
        SessionPRFacts: {
            /** @enum {string} */
            ci: "unknown" | "pending" | "passing" | "failing";
            /** @enum {string} */
            mergeability: "unknown" | "mergeable" | "conflicting" | "blocked" | "unstable";
            number: number;
            /** @enum {string} */
            review: "none" | "approved" | "changes_requested" | "review_required";
            reviewComments: boolean;
            /** @enum {string} */
            state: "draft" | "open" | "merged" | "closed";
            /** Format: date-time */
            updatedAt: string;
            url: string;
        };
        AttachmentInput: {
            data: string;
            mimeType?: string;
        };
        SessionPRFailingCheck: {
            conclusion: string;
            name: string;
            /** @enum {string} */
            status: "failed" | "cancelled";
            url?: string;
        };
        SessionPRCISummary: {
            autoInjectCI: boolean;
            failingChecks: components["schemas"]["SessionPRFailingCheck"][];
            /** @enum {string} */
            state: "unknown" | "pending" | "passing" | "failing";
        };
        SessionPRConflictFile: {
            path: string;
            url?: string;
        };
        SessionPRMergeabilitySummary: {
            conflictFiles?: components["schemas"]["SessionPRConflictFile"][];
            prUrl: string;
            reasons: string[];
            /** @enum {string} */
            state: "unknown" | "mergeable" | "conflicting" | "blocked" | "unstable";
        };
        SessionPRReviewCommentLink: {
            autoInjectReview: boolean;
            body?: string;
            file?: string;
            line?: number;
            url?: string;
        };
        SessionPRUnresolvedReviewer: {
            count: number;
            isBot?: boolean;
            links: components["schemas"]["SessionPRReviewCommentLink"][];
            reviewUrl?: string;
            reviewerId: string;
        };
        SessionPRReviewEntry: {
            autoInjectReview: boolean;
            body?: string;
            isBot?: boolean;
            reviewUrl?: string;
            reviewerId: string;
            /** Format: date-time */
            submittedAt: string;
            /** @enum {string} */
            verdict: "none" | "approved" | "changes_requested" | "review_required";
        };
        SessionPRReviewSummary: {
            /** @enum {string} */
            decision: "none" | "approved" | "changes_requested" | "review_required";
            hasUnresolvedHumanComments: boolean;
            resolvedBy?: components["schemas"]["SessionPRUnresolvedReviewer"][];
            reviews?: components["schemas"]["SessionPRReviewEntry"][];
            unresolvedBy: components["schemas"]["SessionPRUnresolvedReviewer"][];
        };
        SessionPRSummary: {
            additions: number;
            author: string;
            changedFiles: number;
            ci: components["schemas"]["SessionPRCISummary"];
            /** Format: date-time */
            ciObservedAt?: string;
            /** Format: date-time */
            createdAt?: null | string;
            deletions: number;
            headSha: string;
            htmlUrl?: string;
            mergeability: components["schemas"]["SessionPRMergeabilitySummary"];
            number: number;
            /** Format: date-time */
            observedAt?: string;
            /** @enum {string} */
            provider: "github" | "gitlab";
            repo: string;
            review: components["schemas"]["SessionPRReviewSummary"];
            /** Format: date-time */
            reviewObservedAt?: string;
            sourceBranch: string;
            /** @enum {string} */
            state: "draft" | "open" | "merged" | "closed";
            /** Format: date-time */
            stateChangedAt?: null | string;
            targetBranch: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
            url: string;
        };
        ReviewRun: {
            autoInjectReview: boolean;
            batchId: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deliveredAt?: null | string;
            githubReviewId: string;
            harness: string;
            id: string;
            prUrl: string;
            reviewId: string;
            sessionId: string;
            status: string;
            targetSha: string;
            /** @enum {string} */
            triggerSource: "manual" | "auto";
            verdict: string;
        };
        PRReviewState: {
            latestRun?: components["schemas"]["ReviewRun"];
            prNumber: number;
            prUrl: string;
            previousRun?: components["schemas"]["ReviewRun"];
            /** @enum {string} */
            status: "needs_review" | "running" | "up_to_date" | "changes_requested" | "ineligible";
            targetSha: string;
            title: string;
        };
        WorkspaceFileSummary: {
            additions: number;
            binary: boolean;
            deletions: number;
            path: string;
            previousPath?: string;
            /** Format: int64 */
            size: number;
            /** @enum {string} */
            status: "unmodified" | "modified" | "added" | "deleted" | "renamed";
        };
    };
    responses: {
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        WorkerUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        WorkerForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Canonical control-plane error with request correlation. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        SharedBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedConflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedUnprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedNotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        SharedInternalError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Canonical shared /api/v1 error envelope. */
        SharedErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: {
        /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
         *     multiple organizations. It is never an authority for control-plane
         *     admin routes, whose orgId path parameter remains authoritative.
         *      */
        XAOOrg: string;
        OrgId: string;
        ProjectId: string;
        SessionId: string;
        OperationId: string;
        InstallationId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeGoogleIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleIdentityExchange"];
            };
        };
        responses: {
            /** @description AO session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AOSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshCloudSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenInput"];
            };
        };
        responses: {
            /** @description Rotated AO session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AOSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logoutCloudSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenInput"];
            };
        };
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account and memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listHostedProjects: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO project list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    getHostedProject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO project detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGetResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    listHostedSessions: {
        parameters: {
            query?: {
                project?: string;
                active?: boolean | null;
                orchestratorOnly?: boolean | null;
                fresh?: boolean | null;
            };
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO session list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionsResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    spawnHostedSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpawnSessionRequest"];
            };
        };
        responses: {
            /** @description Canonical AO session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpawnSessionResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            409: components["responses"]["SharedConflict"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    getHostedSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    sendHostedSessionMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSessionMessageRequest"];
            };
        };
        responses: {
            /** @description Canonical AO send result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendSessionMessageResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            409: components["responses"]["SharedConflict"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    listHostedSessionPullRequests: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO pull-request facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionPRsResponse"];
                };
            };
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
            501: components["responses"]["SharedNotImplemented"];
        };
    };
    listHostedSessionReviews: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO review state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReviewsResponse"];
                };
            };
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            422: components["responses"]["SharedUnprocessable"];
            501: components["responses"]["SharedNotImplemented"];
        };
    };
    listHostedWorkspaceFiles: {
        parameters: {
            query?: never;
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO workspace file list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWorkspaceFilesResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
            501: components["responses"]["SharedNotImplemented"];
        };
    };
    readHostedWorkspaceFile: {
        parameters: {
            query: {
                path: string;
            };
            header?: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO workspace file and diff. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFileResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
            501: components["responses"]["SharedNotImplemented"];
        };
    };
    createSandboxTerminalConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description Hosted /api/v1 tenant selector. Required when the principal belongs to
                 *     multiple organizations. It is never an authority for control-plane
                 *     admin routes, whose orgId path parameter remains authoritative.
                 *      */
                "X-AO-Org"?: components["parameters"]["XAOOrg"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalConnectionRequest"];
            };
        };
        responses: {
            /** @description One-time sandbox mux connection metadata. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalConnection"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["SharedUnauthorized"];
            403: components["responses"]["SharedForbidden"];
            404: components["responses"]["SharedNotFound"];
            409: components["responses"]["SharedConflict"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    createWorkspacePlacement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspacePlacementInput"];
            };
        };
        responses: {
            /** @description Placement operation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacementOperation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getWorkspacePlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                operationId: components["parameters"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current placement operation state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacementOperation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listGitHubInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization GitHub App installations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    startGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single-use installation flow started. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallationStart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    disconnectGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation disconnected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listGitHubInstallationRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories visible through the installation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    setGitHubRepositoryAllowlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubRepositoryAllowlistInput"];
            };
        };
        responses: {
            /** @description Updated repository allowlist. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    syncGitHubInstallation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synchronized repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    completeGitHubInstallation: {
        parameters: {
            query: {
                state: string;
                installation_id: number;
                setup_action?: string;
                code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation linked when no completion redirect is configured. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallation"];
                };
            };
            /** @description Browser redirected to the configured completion URL. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": string;
                "X-GitHub-Delivery": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Authenticated delivery accepted or deduplicated. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubWebhookAcceptance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    acknowledgeWorkerBootstrap: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerBootstrapInput"];
            };
        };
        responses: {
            /** @description Bootstrap delivery consumed or replayed idempotently. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerBootstrapGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getWorkerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability-scoped worker and placement status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    heartbeatWorker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerHeartbeatInput"];
            };
        };
        responses: {
            /** @description Liveness recorded without returning a replacement bearer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    sendWorkerSessionMessage: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSessionMessageRequest"];
            };
        };
        responses: {
            /** @description Canonical AO send result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendSessionMessageResponse"];
                };
            };
            400: components["responses"]["SharedBadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["SharedNotFound"];
            409: components["responses"]["SharedConflict"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    listWorkerSessionPullRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO pull-request facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSessionPRsResponse"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["SharedNotFound"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    listWorkerSessionReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical AO review state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReviewsResponse"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            422: components["responses"]["SharedUnprocessable"];
            500: components["responses"]["SharedInternalError"];
        };
    };
    requestWorkerCheckoutGrant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCheckoutGrantInput"];
            };
        };
        responses: {
            /** @description Checkout delivery accepted. */
            202: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerCheckoutGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
