/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cloud/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exchangeGoogleIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshCloudSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutCloudSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listWorkspacePlacements"];
        put?: never;
        /** @description Accepts the asynchronous project-placement saga. A successful response
         *     is placement acceptance, not a product project response. Poll the
         *     returned workspace until ready; project discovery remains exclusively
         *     on the separate code-first application API and client.
         *      */
        post: operations["createWorkspacePlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get: operations["getWorkspacePlacement"];
        put?: never;
        post?: never;
        delete: operations["deleteWorkspacePlacement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/workspaces/{workspaceId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeWorkspacePlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/provider-connections": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listProviderConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/provider-connections/agents/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putAgentProviderConnection"];
        post?: never;
        delete: operations["deleteAgentProviderConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/sessions/{sessionId}/terminal-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTerminalTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/sandbox/terminal-tickets/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically consumes a one-time ticket for the bound sandbox tuple. */
        post: operations["consumeTerminalTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get: operations["listGitHubInstallations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startGitHubInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["disconnectGitHubInstallation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get: operations["listGitHubInstallationRepositories"];
        put: operations["setGitHubRepositoryAllowlist"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/orgs/{orgId}/github/installations/{installationId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncGitHubInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/github/installations/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["completeGitHubInstallation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/github/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atomically consumes one scoped bootstrap delivery. The bearer used for
         *     this request was delivered out of band in /run/ao/capability and is not
         *     repeated in either request or response.
         *      */
        post: operations["acknowledgeWorkerBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeatWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkerSessions"];
        put?: never;
        post: operations["createWorkerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getWorkerSession"];
        put?: never;
        post?: never;
        delete: operations["deleteWorkerSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkerSessionMessages"];
        put?: never;
        post: operations["sendWorkerSessionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/pr/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimWorkerSessionPullRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/pr": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkerSessionPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["listWorkerSessionReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/sessions/{sessionId}/reviews/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitWorkerSessionReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishWorkerEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/turns/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimWorkerTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/turns/{turnId}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        get: operations["getWorkerTurnCancellation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/turns/{turnId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeWorkerTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/turns/{turnId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["failWorkerTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/transport/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimWorkerTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/transport/{requestId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeWorkerTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/transport/{requestId}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["failWorkerTransport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud/v1/worker/checkout-grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requests one scoped checkout delivery. The control plane returns only
         *     delivery state; repository credentials are installed by the sandbox
         *     delivery mechanism and never appear in JSON, argv, environment, or git
         *     configuration.
         *      */
        post: operations["requestWorkerCheckoutGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: string;
            code: string;
            message: string;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        GoogleIdentityExchange: {
            idToken: string;
        };
        RefreshTokenInput: {
            refreshToken: string;
        };
        CloudTokenSet: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
        };
        OrganizationMembership: {
            /** Format: uuid */
            orgId: string;
            orgSlug: string;
            displayName: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        CurrentAccount: {
            user: components["schemas"]["CurrentUser"];
            organizations: components["schemas"]["OrganizationMembership"][];
        };
        CreateWorkspacePlacementInput: {
            displayName?: string;
            /** Format: uri */
            repositoryUrl?: string;
            /** @description Authoritative branch passed through the placement saga. */
            defaultBranch?: string;
            config?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        WorkspacePlacementState: "pending" | "failed" | "ready";
        WorkspacePlacement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orgId: string;
            /** Format: uuid */
            ownerUserId: string;
            state: components["schemas"]["WorkspacePlacementState"];
            /** @description Present only when state is ready; discovery uses the separate application client. */
            projectId?: string;
            /** @description Human-readable pending progress or terminal failure detail. */
            message?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspacePlacementPage: {
            workspaces: components["schemas"]["WorkspacePlacement"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        PageInfo: {
            hasMore: boolean;
            nextCursor?: string;
        };
        PlacementFailure: {
            code: string;
            message: string;
        };
        GitHubInstallation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orgId: string;
            /** @constant */
            provider: "github";
            accountLogin: string;
            accountType: string;
            appSlug: string;
            repositorySelection: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GitHubInstallationList: {
            installations: components["schemas"]["GitHubInstallation"][];
        };
        GitHubInstallationStart: {
            /** Format: uri */
            installUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        GitHubRepository: {
            id: string;
            fullName: string;
            private: boolean;
            allowed: boolean;
        };
        GitHubRepositoryList: {
            repositories: components["schemas"]["GitHubRepository"][];
        };
        GitHubRepositoryAllowlistInput: {
            repositories: string[];
        };
        GitHubWebhookAcceptance: {
            /** @enum {string} */
            status: "accepted" | "duplicate";
        };
        ProviderConnectionList: {
            providerConnections: components["schemas"]["RedactedProviderConnection"][];
        };
        ProviderConnectionResponse: {
            providerConnection: components["schemas"]["RedactedProviderConnection"];
        };
        RedactedProviderConnection: {
            /** @enum {string} */
            provider: "claude-code" | "codex" | "cursor";
            configured: boolean;
            label?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PutAgentProviderConnectionInput: {
            /** Format: password */
            credential: string;
            label?: string;
        };
        TerminalTicketRequest: {
            scopes: components["schemas"]["TerminalTicketScope"][];
        };
        /** @enum {string} */
        TerminalTicketScope: "terminal:read" | "terminal:operate" | "workspace:observe";
        TerminalTicket: {
            /**
             * Format: uri
             * @description Authenticated sandbox mux WebSocket URL, never a control-plane relay URL.
             */
            connectionUrl: string;
            /** @description Single-use ticket offered only as the WebSocket subprotocol. */
            ticket: string;
            scopes: components["schemas"]["TerminalTicketScope"][];
            /** Format: date-time */
            expiresAt: string;
            /** @constant */
            protocol: "ao.mux.v1";
        };
        TerminalTicketRedemption: {
            ticket: string;
            sandboxId: string;
            workspaceId: string;
            sessionId: string;
        };
        TerminalTicketGrant: {
            sandboxId: string;
            workspaceId: string;
            sessionId: string;
            scopes: components["schemas"]["TerminalTicketScope"][];
            /** Format: date-time */
            expiresAt: string;
        };
        WorkerBootstrapInput: {
            /** Format: uuid */
            deliveryId: string;
            version: string;
            capabilities: string[];
        };
        WorkerBootstrapGrant: {
            /** Format: uuid */
            deliveryId: string;
            /** @enum {string} */
            state: "consumed";
            scope: components["schemas"]["WorkerScope"];
            /** Format: date-time */
            consumedAt: string;
        };
        WorkerScope: {
            /** Format: uuid */
            orgId: string;
            /** Format: uuid */
            workspaceId: string;
            sessionId: string;
            /** @enum {string} */
            role: "coordinator" | "worker";
        };
        WorkerHeartbeatInput: {
            version: string;
            capabilities: string[];
        };
        WorkerStatus: {
            scope: components["schemas"]["WorkerScope"];
            /** @enum {string} */
            placementState: "pending" | "running" | "stopping" | "stopped" | "failed";
            /** Format: date-time */
            observedAt: string;
        };
        WorkerSessionCreateInput: {
            projectId: string;
            /** @enum {string} */
            role: "coordinator" | "worker";
            harness: string;
            prompt?: string;
        };
        WorkerSessionRecord: {
            id: string;
            /** Format: uuid */
            workspaceId: string;
            projectId: string;
            /** @enum {string} */
            role: "coordinator" | "worker";
            /** @enum {string} */
            state: "pending" | "running" | "stopping" | "stopped" | "failed";
            failure?: components["schemas"]["PlacementFailure"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkerSessionRecordPage: {
            sessions: components["schemas"]["WorkerSessionRecord"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        WorkerMessageInput: {
            message: string;
        };
        WorkerMessage: {
            id: string;
            sessionId: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        WorkerMessagePage: {
            messages: components["schemas"]["WorkerMessage"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        WorkerPullRequestClaimInput: {
            /** Format: uri */
            url: string;
        };
        WorkerPullRequest: {
            /** Format: uri */
            url: string;
            number: number;
            /** @enum {string} */
            state: "draft" | "open" | "merged" | "closed";
            title: string;
            headSha?: string;
        };
        WorkerPullRequestPage: {
            pullRequests: components["schemas"]["WorkerPullRequest"][];
        };
        WorkerReview: {
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "passed" | "failed" | "cancelled";
            /** @enum {string} */
            verdict?: "approve" | "comment" | "request_changes";
            summary?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkerReviewPage: {
            reviews: components["schemas"]["WorkerReview"][];
        };
        WorkerReviewSubmitInput: {
            /** @enum {string} */
            verdict: "approve" | "comment" | "request_changes";
            summary: string;
        };
        WorkerEventInput: {
            /** @enum {string} */
            type: "worker.ready" | "chat.assistant_delta" | "agent.activity";
            payload: {
                [key: string]: unknown;
            };
        };
        WorkerOKResponse: {
            /** @constant */
            ok: true;
        };
        WorkerTurn: {
            /** Format: uuid */
            id: string;
            prompt: string;
            attempt: number;
            cancelRequested: boolean;
        };
        WorkerClaimTurnResponse: {
            turn: components["schemas"]["WorkerTurn"] | null;
        };
        WorkerCancellationResponse: {
            requested: boolean;
        };
        WorkerCompleteTurnInput: {
            attempt: number;
            cancelled?: boolean;
        };
        WorkerFailTurnInput: {
            attempt: number;
            error: string;
        };
        WorkerFinishTurnResponse: {
            /** @constant */
            ok: true;
            alreadyFinished: boolean;
        };
        WorkerWorkspaceTransportRequest: {
            /** Format: uuid */
            id: string;
            attempt: number;
            /** @enum {string} */
            kind: "workspace.list" | "workspace.read" | "workspace.write" | "workspace.diff";
            payload: {
                [key: string]: unknown;
            };
        };
        WorkerClaimTransportResponse: {
            request: components["schemas"]["WorkerWorkspaceTransportRequest"] | null;
        };
        WorkerCompleteTransportInput: {
            attempt: number;
            response: {
                [key: string]: unknown;
            };
        };
        WorkerFailTransportInput: {
            attempt: number;
            code: string;
            message: string;
        };
        WorkerCheckoutGrantInput: {
            /** Format: uuid */
            deliveryId: string;
            repositoryId: string;
            /** @enum {string} */
            operation: "clone" | "fetch";
        };
        WorkerCheckoutGrant: {
            /** Format: uuid */
            deliveryId: string;
            repositoryId: string;
            /** @enum {string} */
            operation: "clone" | "fetch";
            /** @enum {string} */
            state: "pending" | "delivered" | "failed" | "expired";
            /** Format: date-time */
            expiresAt: string;
            failure?: components["schemas"]["PlacementFailure"];
        };
    };
    responses: {
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        WorkerUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        WorkerForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Canonical control-plane error with request correlation. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        OrgId: string;
        SessionId: string;
        WorkspaceId: string;
        InstallationId: string;
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
        Provider: "claude-code" | "codex" | "cursor";
        TurnId: string;
        RequestId: string;
        Attempt: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeGoogleIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleIdentityExchange"];
            };
        };
        responses: {
            /** @description AO session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTokenSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshCloudSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenInput"];
            };
        };
        responses: {
            /** @description Rotated AO session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTokenSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logoutCloudSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenInput"];
            };
        };
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account and memberships. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listWorkspacePlacements: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-scoped workspace placement page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacementPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createWorkspacePlacement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspacePlacementInput"];
            };
        };
        responses: {
            /** @description Placement operation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getWorkspacePlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current placement operation state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteWorkspacePlacement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace deletion accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    resumeWorkspacePlacement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace resume accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePlacement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listProviderConnections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted organization provider connections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConnectionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    putAgentProviderConnection: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutAgentProviderConnectionInput"];
            };
        };
        responses: {
            /** @description Redacted provider connection metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConnectionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAgentProviderConnection: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                provider: components["parameters"]["Provider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider connection deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createTerminalTicket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalTicketRequest"];
            };
        };
        responses: {
            /** @description One-time ticket and direct sandbox mux metadata. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalTicket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    consumeTerminalTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalTicketRedemption"];
            };
        };
        responses: {
            /** @description Scope grant for the exact sandbox, workspace, and session. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerminalTicketGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listGitHubInstallations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization GitHub App installations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    startGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single-use installation flow started. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallationStart"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    disconnectGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation disconnected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listGitHubInstallationRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories visible through the installation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    setGitHubRepositoryAllowlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubRepositoryAllowlistInput"];
            };
        };
        responses: {
            /** @description Updated repository allowlist. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    syncGitHubInstallation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                orgId: components["parameters"]["OrgId"];
                installationId: components["parameters"]["InstallationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synchronized repositories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    completeGitHubInstallation: {
        parameters: {
            query: {
                state: string;
                installation_id: number;
                setup_action?: string;
                code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installation linked when no completion redirect is configured. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubInstallation"];
                };
            };
            /** @description Browser redirected to the configured completion URL. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    receiveGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": string;
                "X-GitHub-Delivery": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Authenticated delivery accepted or deduplicated. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubWebhookAcceptance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    acknowledgeWorkerBootstrap: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerBootstrapInput"];
            };
        };
        responses: {
            /** @description Bootstrap delivery consumed or replayed idempotently. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerBootstrapGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getWorkerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability-scoped worker and placement status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    heartbeatWorker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerHeartbeatInput"];
            };
        };
        responses: {
            /** @description Liveness recorded without returning a replacement bearer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerStatus"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listWorkerSessions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability-scoped session page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerSessionRecordPage"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createWorkerSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerSessionCreateInput"];
            };
        };
        responses: {
            /** @description Worker session creation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerSessionRecord"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getWorkerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability-scoped worker session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerSessionRecord"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteWorkerSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worker session deletion accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerSessionRecord"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listWorkerSessionMessages: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability-scoped message page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerMessagePage"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    sendWorkerSessionMessage: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerMessageInput"];
            };
        };
        responses: {
            /** @description Message accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerMessage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    claimWorkerSessionPullRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerPullRequestClaimInput"];
            };
        };
        responses: {
            /** @description Pull request claim result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPullRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listWorkerSessionPullRequests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pull-request facts visible to the capability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPullRequestPage"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listWorkerSessionReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review state visible to the capability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerReviewPage"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    submitWorkerSessionReview: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerReviewSubmitInput"];
            };
        };
        responses: {
            /** @description Review submitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerReview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    publishWorkerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerEventInput"];
            };
        };
        responses: {
            /** @description Event durably accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerOKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    claimWorkerTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimed turn or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerClaimTurnResponse"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
        };
    };
    getWorkerTurnCancellation: {
        parameters: {
            query: {
                attempt: components["parameters"]["Attempt"];
            };
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation state for the fenced attempt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerCancellationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    completeWorkerTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCompleteTurnInput"];
            };
        };
        responses: {
            /** @description Fenced completion accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerFinishTurnResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    failWorkerTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnId: components["parameters"]["TurnId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerFailTurnInput"];
            };
        };
        responses: {
            /** @description Fenced failure accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerFinishTurnResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    claimWorkerTransport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimed non-terminal transport request or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerClaimTransportResponse"];
                };
            };
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
        };
    };
    completeWorkerTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCompleteTransportInput"];
            };
        };
        responses: {
            /** @description Transport result recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerOKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    failWorkerTransport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerFailTransportInput"];
            };
        };
        responses: {
            /** @description Transport failure recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerOKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    requestWorkerCheckoutGrant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCheckoutGrantInput"];
            };
        };
        responses: {
            /** @description Checkout delivery accepted. */
            202: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerCheckoutGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["WorkerUnauthorized"];
            403: components["responses"]["WorkerForbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
