/**
 * Team Prompt Builder — 8-layer skill injection for ao-teams agents.
 *
 * Skill injection order (later layers override earlier on conflict):
 *   0. Toolkit skill     (ao-bus command reference)
 *   1. Project skills    (skills: in YAML)
 *   1.5 Project learnings (.ao/learnings/*.md)
 *   2. Agent skills      (per-agent skills: in YAML)
 *   3. Role prompt       (prompt_file: in YAML)
 *   4. Phase instructions (generated by phase engine)
 *   5. Task context      (issue body, plan summary)
 *   6. Messages          (pre-loaded from ao-inbox)
 *   7. Prior work        (git diff, review report, test output)
 */

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { Phase, TeamAgentConfig, Plan, BusMessage } from "@composio/ao-core";

export interface TeamPromptConfig {
  /** Agent name */
  agentName: string;
  /** Agent role */
  role: string;
  /** Current phase */
  phase: Phase;
  /** Path to worktree */
  worktreePath: string;
  /** Path to .agents/ directory */
  agentsDir: string;
  /** Assigned files (exclusive write scope) */
  fileScope: string[];
  /** Shared files (read-only in implement) */
  sharedFiles: string[];
  /** Agent config from team definition */
  agentConfig?: TeamAgentConfig;
  /** Global skill file paths */
  globalSkills?: string[];
  /** Phase-specific instructions */
  phaseInstructions?: string;
  /** Task description or issue body */
  taskDescription?: string;
  /** Current plan */
  plan?: Plan;
  /** Messages for this agent */
  messages?: BusMessage[];
  /** Prior work context (git diff, review report, etc.) */
  priorWork?: string;
  /** Content of ao-bus.md skill file */
  toolkitSkill?: string;
  /** Learnings content from .ao/learnings/ */
  learningsContent?: string;
}

/**
 * Build a complete prompt for an agent activation, following
 * the 8-layer skill injection order.
 */
export function buildTeamPrompt(config: TeamPromptConfig): string {
  const sections: string[] = [];

  // Layer 0: Toolkit skill (ao-bus command reference)
  if (config.toolkitSkill) {
    sections.push(config.toolkitSkill);
  } else {
    sections.push(generateInlineToolkitSkill(config));
  }

  // Layer 1: Project skills (global skill files from YAML)
  if (config.globalSkills) {
    for (const skillPath of config.globalSkills) {
      const content = safeReadFile(resolve(config.worktreePath, skillPath));
      if (content) {
        sections.push(content);
      }
    }
  }

  // Layer 1.5: Project learnings (.ao/learnings/)
  if (config.learningsContent) {
    sections.push(`## Project Learnings\n\n${config.learningsContent}`);
  }

  // Layer 2: Agent skills (per-agent skill files from YAML)
  if (config.agentConfig?.skills) {
    for (const skillPath of config.agentConfig.skills) {
      const content = safeReadFile(resolve(config.worktreePath, skillPath));
      if (content) {
        sections.push(content);
      }
    }
  }

  // Layer 3: Role prompt (prompt_file from YAML)
  if (config.agentConfig?.promptFile) {
    const content = safeReadFile(resolve(config.worktreePath, config.agentConfig.promptFile));
    if (content) {
      sections.push(content);
    }
  }

  // Layer 4: Phase instructions (generated by phase engine)
  if (config.phaseInstructions) {
    sections.push(`## Phase: ${config.phase}\n\n${config.phaseInstructions}`);
  }

  // Layer 5: Task context
  if (config.taskDescription) {
    sections.push(`## Task\n\n${config.taskDescription}`);
  }
  if (config.plan) {
    sections.push(formatPlanContext(config.plan, config.agentName));
  }

  // Layer 6: Messages (pre-loaded from inbox)
  if (config.messages && config.messages.length > 0) {
    sections.push(formatMessages(config.messages));
  }

  // Layer 7: Prior work (git diff, review report, test output)
  if (config.priorWork) {
    sections.push(`## Prior Work\n\n${config.priorWork}`);
  }

  return sections.join("\n\n---\n\n");
}

/** Generate inline toolkit skill when ao-bus.md is not available */
function generateInlineToolkitSkill(config: TeamPromptConfig): string {
  const bin = `${config.agentsDir}/bin/ao-bus-cli`;
  const flags = `--agent ${config.agentName} --phase ${config.phase}`;

  return [
    "# ao-teams Agent Toolkit",
    "",
    "You are part of a coordinated team. Use these commands to communicate and report status.",
    "",
    "## Commands",
    "",
    "```bash",
    "# Report status",
    `${bin} ${flags} status done          # report phase complete`,
    `${bin} ${flags} status working --file <path>  # report current work`,
    "",
    "# Messages",
    `${bin} ${flags} msg <to> "<content>"  # send message to another agent`,
    `${bin} ${flags} inbox                 # read messages for you`,
    `${bin} ${flags} inbox --from <agent>  # filter by sender`,
    "",
    "# Context",
    `${bin} ${flags} context               # your role, phase, scope`,
    `${bin} ${flags} context --files        # assigned files`,
    `${bin} ${flags} context --criteria     # acceptance criteria`,
    "",
    "# Artifacts",
    `echo "<content>" | ${bin} ${flags} artifact write <name>`,
    `${bin} ${flags} artifact read <name>`,
    "",
    "# Learnings",
    `${bin} ${flags} learn convention "<description>"`,
    `${bin} ${flags} learn pitfall "<description>"`,
    `${bin} ${flags} learn decision "<description>"`,
    "```",
    "",
    `## Your Role: ${config.role}`,
    `## Current Phase: ${config.phase}`,
    `## Assigned Files: ${config.fileScope.join(", ") || "(none)"}`,
    `## Shared Files: ${config.sharedFiles.join(", ") || "(none)"}`,
    "",
    "**IMPORTANT:** Always run the status done command when your phase work is complete.",
  ].join("\n");
}

/** Format plan context for prompt injection */
function formatPlanContext(plan: Plan, agentName: string): string {
  const lines: string[] = ["## Plan", "", `Summary: ${plan.summary}`, ""];

  const myUnits = plan.workUnits.filter((wu) => wu.assignedTo === agentName);
  if (myUnits.length > 0) {
    lines.push("### Your Work Units:");
    for (const wu of myUnits) {
      lines.push(`- **${wu.id}**: ${wu.description}`);
      lines.push(`  Files: ${wu.files.join(", ")}`);
      lines.push(`  Criteria: ${wu.criteria}`);
    }
  }

  const otherUnits = plan.workUnits.filter((wu) => wu.assignedTo !== agentName);
  if (otherUnits.length > 0) {
    lines.push("", "### Other Work Units (for context):");
    for (const wu of otherUnits) {
      lines.push(`- **${wu.id}** (${wu.assignedTo}): ${wu.description}`);
    }
  }

  if (plan.sharedFiles.length > 0) {
    lines.push("", `Shared files: ${plan.sharedFiles.join(", ")}`);
  }

  return lines.join("\n");
}

/** Format messages for prompt injection */
function formatMessages(messages: BusMessage[]): string {
  const lines: string[] = ["## Messages"];
  for (const msg of messages) {
    const priorityTag = msg.priority ? ` [${msg.priority}]` : "";
    lines.push(`[${msg.seq}] ${msg.from}${priorityTag}: ${msg.content}`);
  }
  return lines.join("\n");
}

/** Safely read a file, returning null on failure */
function safeReadFile(path: string): string | null {
  if (!existsSync(path)) return null;
  try {
    return readFileSync(path, "utf-8").trim();
  } catch {
    return null;
  }
}
